# Generated by Django 3.2.13 on 2022-06-26 12:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('created_datetime', models.DateTimeField(auto_now=True, verbose_name='Last updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=12)),
                ('last_name', models.CharField(blank=True, max_length=12)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkerShift',
            fields=[
                ('created_datetime', models.DateTimeField(auto_now=True, verbose_name='Last updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift', models.IntegerField(choices=[(0, '0 - 8'), (1, '8 - 16'), (2, '19 - 24')], default=0)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worker.worker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
